### ISSUE TITLE
`SyntaxError: invalid syntax` in `uuid`

### ISSUE THREAD

**Issue by mdwalters** [meower-media-co/Meower-Server#139]
```
Traceback (most recent call last):
  File "meower.py", line 2, in <module>
    import uuid
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/uuid.py", line 138
    if not 0 <= time_low < 1<<32L:
                                ^
SyntaxError: invalid syntax
```

**Comment by showierdata9978** [comment]
not our issue

 raise the issue at https://github.com/python/cpython, because thats where the uuid pkg is made

**Comment by mdwalters** [comment]
ok

**Comment by MikeDev101** [comment]
Closing due to inactivity
