### ISSUE TITLE
CL4: Exception was raised: "'User' object has no attribute 'get_following'"

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#146]
@tnix100 

Issue: CL4 api endpoint `authenticate` command is not functional
Log: 
```
[2023-02-02 10:07:30,913 | 1675350450.913019] (24412 - MainThread) INFO: Cloudlink server v0.1.9.2
[2023-02-02 10:07:30,957 | 1675350450.957789] (24412 - MainThread) INFO: server listening on 0.0.0.0:3001
[2023-02-02 10:08:33,186 | 1675350513.186868] (24412 - MainThread) INFO: connection open
[2023-02-02 10:08:33,186 | 1675350513.186868] (24412 - MainThread) INFO: Client 0 connected: 127.0.0.1
[2023-02-02 10:19:02,857 | 1675351142.857281] (24412 - MainThread) ERROR: Exception was raised: "'User' object has no attribute 'get_following'"
Traceback (most recent call last):
  File "D:\meower-server\meower\run_cl4.py", line 8, in <module>
    cl.run(ip="0.0.0.0", port=3001)
  File "D:\meower-server\meower\src\cl4\cloudlink\server\server.py", line 76, in run
    self.asyncio.run(self.__run__(ip, port))
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 604, in run_forever
    self._run_once()
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 236, in handler
    await self.ws_handler(self)
  File "D:\meower-server\meower\src\cl4\cloudlink\server\server.py", line 563, in __handler__
    result = await self.__run_method__(client, message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\cl4\cloudlink\server\server.py", line 475, in __run_method__
    return await self.__cl_method_handler__(client, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\cl4\cloudlink\server\server.py", line 410, in __cl_method_handler__
    await method(client, message, listener)
  File "D:\meower-server\meower\src\cl4\commands.py", line 60, in authenticate
    "following": session.user.get_following(),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'get_following'

[2023-02-02 10:19:02,864 | 1675351142.864737] (24412 - MainThread) INFO: Client 0 disconnected: 127.0.0.1 - Code 1011 and reason "Unexpected exception was raised"
[2023-02-02 10:19:02,873 | 1675351142.873714] (24412 - MainThread) INFO: connection closed
```

**Comment by tnix100** [comment]
Fixed within commit [d054a47](https://github.com/meower-media-co/Meower-Server/commit/d054a47cc3d8a3265bd3cbea17d484076a9280a6)
