### ISSUE TITLE
[cl4] post.deleted - Post object has no attribute deleted

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#150]
**Describe the bug**
CL4 branch bug. Post object does not have the attribute "deleted", preventing fetching of new posts.

**To Reproduce**
1. Authenticate API
2. Make a POST request to /v1/home with a new post as content
3. Make a GET request to /v1/home
4. Error...

**Expected behavior**
After making a post with POST /v1/home and using GET /v1/home, a array of post objects should populate.

**Logs**
```
Error while handling error: 'NoneType' object has no attribute '__name__'
Stack: Traceback (most recent call last):
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\app.py", line 968, in handle_request
    response = await response
               ^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\api\home.py", line 30, in v1_get_feed
    fetched_posts = posts.get_feed(request.ctx.user, before=request.args.get("before"), after=request.args.get("after"), limit=int(request.args.get("limit", 25)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\entities\posts.py", line 346, in get_feed
    if post.deleted or (post.id in post_ids):
       ^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'deleted'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\handlers.py", line 144, in response
    response = self.default(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\api\errors.py", line 23, in default
    "error": exception.error,
             ^^^^^^^^^^^^^^^
AttributeError: 'AttributeError' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\app.py", line 813, in handle_exception
    response = self.error_handler.response(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\handlers.py", line 153, in response
    error_logger.exception(response_message, handler.__name__, url)
                                             ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by tnix100** [comment]
You just need to replace '.deleted' with '.deleted_at'

**Comment by MikeDev101** [comment]
Will patch in new commit

**Comment by MikeDev101** [comment]
Applied in https://github.com/meower-media-co/Meower-Server/commit/0243e64de5fd4cc6edceb44b8238bd78742f3ff3, closing
