### ISSUE TITLE
[cl4] user.get_following - User object has no attribute get_following

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Server#151]
**Describe the bug**
CL4 branch bug. Attempting to get the homepage feed results in an error for an invalid attribute.

**To Reproduce**
1. Authenticate API
2. Make a POST /v1/home with a new post
3. GET /v1/home
4. Error.

**Fix**
Refactor user.get_following() with user.get_following_ids()

**Logs**
```
Error while handling error: 'NoneType' object has no attribute '__name__'
Stack: Traceback (most recent call last):
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\app.py", line 968, in handle_request
    response = await response
               ^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\api\home.py", line 30, in v1_get_feed
    fetched_posts = posts.get_feed(request.ctx.user, before=request.args.get("before"), after=request.args.get("after"), limit=int(request.args.get("limit", 25)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\entities\posts.py", line 303, in get_feed
    following = user.get_following() #user.get_following_ids()
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'get_following'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\handlers.py", line 144, in response
    response = self.default(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meower-server\meower\src\api\errors.py", line 23, in default
    "error": exception.error,
             ^^^^^^^^^^^^^^^
AttributeError: 'AttributeError' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\app.py", line 813, in handle_exception
    response = self.error_handler.response(request, exception)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mike Renaker\AppData\Local\Programs\Python\Python311\Lib\site-packages\sanic\handlers.py", line 153, in response
    error_logger.exception(response_message, handler.__name__, url)
                                             ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by MikeDev101** [comment]
Fixed in https://github.com/meower-media-co/Meower-Server/commit/f66f790d4a54361dce22a2468e3c61b9dda7938a
